#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : clr-bundles
Version  : 27520
Release  : 33
URL      : https://github.com/clearlinux/clr-bundles/archive/27520.tar.gz
Source0  : https://github.com/clearlinux/clr-bundles/archive/27520.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: clr-bundles-data = %{version}-%{release}

%description
Bundle Definition Files
=======================
**Please submit patches for review to dev@lists.clearlinux.org.**

%package data
Summary: data components for the clr-bundles package.
Group: Data

%description data
data components for the clr-bundles package.


%prep
%setup -q -n clr-bundles-27520

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1548816817
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1548816817
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/clr-bundles/ImageMagick
/usr/share/clr-bundles/R-basic
/usr/share/clr-bundles/R-datasets
/usr/share/clr-bundles/R-extras
/usr/share/clr-bundles/amateur-radio
/usr/share/clr-bundles/ansible
/usr/share/clr-bundles/application-server
/usr/share/clr-bundles/atom
/usr/share/clr-bundles/aws-greengrass-iot
/usr/share/clr-bundles/azure-iot-sdk
/usr/share/clr-bundles/big-data-basic
/usr/share/clr-bundles/blender
/usr/share/clr-bundles/boot-encrypted
/usr/share/clr-bundles/bootloader
/usr/share/clr-bundles/bootloader-extras
/usr/share/clr-bundles/c-basic
/usr/share/clr-bundles/c-basic-legacy
/usr/share/clr-bundles/cloud-api
/usr/share/clr-bundles/cloud-control
/usr/share/clr-bundles/cloud-native-basic
/usr/share/clr-bundles/clr-devops
/usr/share/clr-bundles/clr-installer
/usr/share/clr-bundles/computer-vision-basic
/usr/share/clr-bundles/computer-vision-models
/usr/share/clr-bundles/containers-basic
/usr/share/clr-bundles/containers-basic-dev
/usr/share/clr-bundles/containers-virt
/usr/share/clr-bundles/containers-virt-dev
/usr/share/clr-bundles/cryptography
/usr/share/clr-bundles/cryptoprocessor-management
/usr/share/clr-bundles/cryptoprocessor-management-dev
/usr/share/clr-bundles/database-basic
/usr/share/clr-bundles/database-basic-dev
/usr/share/clr-bundles/desktop
/usr/share/clr-bundles/desktop-apps
/usr/share/clr-bundles/desktop-apps-extras
/usr/share/clr-bundles/desktop-assets
/usr/share/clr-bundles/desktop-autostart
/usr/share/clr-bundles/desktop-awesome
/usr/share/clr-bundles/desktop-dev
/usr/share/clr-bundles/desktop-gnomelibs
/usr/share/clr-bundles/desktop-i3
/usr/share/clr-bundles/desktop-kde
/usr/share/clr-bundles/desktop-kde-apps
/usr/share/clr-bundles/desktop-kde-games
/usr/share/clr-bundles/desktop-kde-libs
/usr/share/clr-bundles/desktop-locales
/usr/share/clr-bundles/dev-utils
/usr/share/clr-bundles/dev-utils-dev
/usr/share/clr-bundles/dev-utils-gui
/usr/share/clr-bundles/devpkg-at-spi2-atk
/usr/share/clr-bundles/devpkg-at-spi2-core
/usr/share/clr-bundles/devpkg-atk
/usr/share/clr-bundles/devpkg-base
/usr/share/clr-bundles/devpkg-cairo
/usr/share/clr-bundles/devpkg-cheese
/usr/share/clr-bundles/devpkg-clutter
/usr/share/clr-bundles/devpkg-clutter-gst
/usr/share/clr-bundles/devpkg-cogl
/usr/share/clr-bundles/devpkg-dbus
/usr/share/clr-bundles/devpkg-elfutils
/usr/share/clr-bundles/devpkg-evolution
/usr/share/clr-bundles/devpkg-evolution-data-server
/usr/share/clr-bundles/devpkg-expat
/usr/share/clr-bundles/devpkg-fontconfig
/usr/share/clr-bundles/devpkg-freetype
/usr/share/clr-bundles/devpkg-fribidi
/usr/share/clr-bundles/devpkg-fuse
/usr/share/clr-bundles/devpkg-gdk-pixbuf
/usr/share/clr-bundles/devpkg-glib
/usr/share/clr-bundles/devpkg-gnome-desktop
/usr/share/clr-bundles/devpkg-graphite
/usr/share/clr-bundles/devpkg-gsettings-desktop-schemas
/usr/share/clr-bundles/devpkg-gst-plugins-base
/usr/share/clr-bundles/devpkg-gstreamer
/usr/share/clr-bundles/devpkg-gtk3
/usr/share/clr-bundles/devpkg-harfbuzz
/usr/share/clr-bundles/devpkg-icu4c
/usr/share/clr-bundles/devpkg-libX11
/usr/share/clr-bundles/devpkg-libXau
/usr/share/clr-bundles/devpkg-libXcomposite
/usr/share/clr-bundles/devpkg-libXdamage
/usr/share/clr-bundles/devpkg-libXdmcp
/usr/share/clr-bundles/devpkg-libXext
/usr/share/clr-bundles/devpkg-libXfixes
/usr/share/clr-bundles/devpkg-libXi
/usr/share/clr-bundles/devpkg-libXinerama
/usr/share/clr-bundles/devpkg-libXrandr
/usr/share/clr-bundles/devpkg-libXrender
/usr/share/clr-bundles/devpkg-libXxf86vm
/usr/share/clr-bundles/devpkg-libdrm
/usr/share/clr-bundles/devpkg-libepoxy
/usr/share/clr-bundles/devpkg-libical
/usr/share/clr-bundles/devpkg-libpciaccess
/usr/share/clr-bundles/devpkg-libpng
/usr/share/clr-bundles/devpkg-libpthread-stubs
/usr/share/clr-bundles/devpkg-libsecret
/usr/share/clr-bundles/devpkg-libsoup
/usr/share/clr-bundles/devpkg-libxcb
/usr/share/clr-bundles/devpkg-libxkbcommon
/usr/share/clr-bundles/devpkg-libxml2
/usr/share/clr-bundles/devpkg-mesa
/usr/share/clr-bundles/devpkg-nspr
/usr/share/clr-bundles/devpkg-nss
/usr/share/clr-bundles/devpkg-openblas
/usr/share/clr-bundles/devpkg-opencv
/usr/share/clr-bundles/devpkg-openmpi
/usr/share/clr-bundles/devpkg-openssl
/usr/share/clr-bundles/devpkg-orc
/usr/share/clr-bundles/devpkg-pango
/usr/share/clr-bundles/devpkg-pcre
/usr/share/clr-bundles/devpkg-pixman
/usr/share/clr-bundles/devpkg-qt3d
/usr/share/clr-bundles/devpkg-qtbase
/usr/share/clr-bundles/devpkg-qtdeclarative
/usr/share/clr-bundles/devpkg-sqlite-autoconf
/usr/share/clr-bundles/devpkg-util-linux
/usr/share/clr-bundles/devpkg-wayland
/usr/share/clr-bundles/devpkg-wayland-protocols
/usr/share/clr-bundles/devpkg-webkitgtk
/usr/share/clr-bundles/devpkg-xorg-server
/usr/share/clr-bundles/devpkg-xorgproto
/usr/share/clr-bundles/devpkg-xz
/usr/share/clr-bundles/devpkg-zlib
/usr/share/clr-bundles/dhcp-server
/usr/share/clr-bundles/django
/usr/share/clr-bundles/domotica
/usr/share/clr-bundles/editors
/usr/share/clr-bundles/editors-dev
/usr/share/clr-bundles/education
/usr/share/clr-bundles/education-preschool
/usr/share/clr-bundles/education-primary
/usr/share/clr-bundles/education-secondary
/usr/share/clr-bundles/education-tertiary
/usr/share/clr-bundles/emacs
/usr/share/clr-bundles/enterprise-login
/usr/share/clr-bundles/firmware-update
/usr/share/clr-bundles/flatpak
/usr/share/clr-bundles/games
/usr/share/clr-bundles/games-dev
/usr/share/clr-bundles/git
/usr/share/clr-bundles/go-basic
/usr/share/clr-bundles/go-basic-dev
/usr/share/clr-bundles/hardware-bluetooth
/usr/share/clr-bundles/hardware-printing
/usr/share/clr-bundles/hardware-wifi
/usr/share/clr-bundles/haskell-basic
/usr/share/clr-bundles/hpc-utils
/usr/share/clr-bundles/java-basic
/usr/share/clr-bundles/java-runtime
/usr/share/clr-bundles/java9-basic
/usr/share/clr-bundles/kde-frameworks5
/usr/share/clr-bundles/kdiff3
/usr/share/clr-bundles/kernel-aws
/usr/share/clr-bundles/kernel-container
/usr/share/clr-bundles/kernel-gce
/usr/share/clr-bundles/kernel-hyperv
/usr/share/clr-bundles/kernel-hyperv-lts
/usr/share/clr-bundles/kernel-hyperv-mini
/usr/share/clr-bundles/kernel-iot-lts2017-preempt-rt
/usr/share/clr-bundles/kernel-iot-lts2018
/usr/share/clr-bundles/kernel-kvm
/usr/share/clr-bundles/kernel-lts
/usr/share/clr-bundles/kernel-native
/usr/share/clr-bundles/kernel-native-dkms
/usr/share/clr-bundles/kernel-networktest
/usr/share/clr-bundles/kernel-oracle
/usr/share/clr-bundles/kernel-pk
/usr/share/clr-bundles/kernel-rt
/usr/share/clr-bundles/koji
/usr/share/clr-bundles/kvm-host
/usr/share/clr-bundles/kvm-host-dev
/usr/share/clr-bundles/kvm-host-extras
/usr/share/clr-bundles/letsencrypt-client
/usr/share/clr-bundles/libX11client
/usr/share/clr-bundles/lightdm
/usr/share/clr-bundles/locales
/usr/share/clr-bundles/lua-basic
/usr/share/clr-bundles/machine-learning-basic
/usr/share/clr-bundles/machine-learning-mycroft
/usr/share/clr-bundles/machine-learning-tensorflow
/usr/share/clr-bundles/machine-learning-web-ui
/usr/share/clr-bundles/mail-utils
/usr/share/clr-bundles/mail-utils-dev
/usr/share/clr-bundles/maker-3dprinting
/usr/share/clr-bundles/maker-cnc
/usr/share/clr-bundles/maker-gis
/usr/share/clr-bundles/mercurial
/usr/share/clr-bundles/mixer
/usr/share/clr-bundles/network-basic
/usr/share/clr-bundles/network-basic-dev
/usr/share/clr-bundles/network-security-monitoring
/usr/share/clr-bundles/network-time-sensitive
/usr/share/clr-bundles/nodejs-basic
/usr/share/clr-bundles/openqa
/usr/share/clr-bundles/openssh-server
/usr/share/clr-bundles/openstack-common
/usr/share/clr-bundles/os-clear-containers
/usr/share/clr-bundles/os-cloudguest
/usr/share/clr-bundles/os-cloudguest-aws
/usr/share/clr-bundles/os-cloudguest-azure
/usr/share/clr-bundles/os-cloudguest-gce
/usr/share/clr-bundles/os-cloudguest-oracle
/usr/share/clr-bundles/os-cloudguest-vmware
/usr/share/clr-bundles/os-clr-on-clr
/usr/share/clr-bundles/os-clr-on-clr-dev
/usr/share/clr-bundles/os-core
/usr/share/clr-bundles/os-core-dev
/usr/share/clr-bundles/os-core-update
/usr/share/clr-bundles/os-core-update-dev
/usr/share/clr-bundles/os-core-webproxy
/usr/share/clr-bundles/os-installer
/usr/share/clr-bundles/os-testsuite
/usr/share/clr-bundles/os-testsuite-0day
/usr/share/clr-bundles/os-testsuite-automotive
/usr/share/clr-bundles/os-testsuite-graphics
/usr/share/clr-bundles/os-testsuite-phoronix
/usr/share/clr-bundles/os-testsuite-phoronix-desktop
/usr/share/clr-bundles/os-testsuite-phoronix-server
/usr/share/clr-bundles/os-utils-gui
/usr/share/clr-bundles/os-utils-gui-dev
/usr/share/clr-bundles/package-builder
/usr/share/clr-bundles/package-utils
/usr/share/clr-bundles/packages
/usr/share/clr-bundles/performance-tools
/usr/share/clr-bundles/perl-basic
/usr/share/clr-bundles/perl-basic-dev
/usr/share/clr-bundles/perl-extras
/usr/share/clr-bundles/php-basic
/usr/share/clr-bundles/pidgin
/usr/share/clr-bundles/pnp-tools-basic
/usr/share/clr-bundles/productivity
/usr/share/clr-bundles/pxe-server
/usr/share/clr-bundles/python-basic
/usr/share/clr-bundles/python-basic-dev
/usr/share/clr-bundles/python-data-science
/usr/share/clr-bundles/python-extras
/usr/share/clr-bundles/python2-basic
/usr/share/clr-bundles/python3-basic
/usr/share/clr-bundles/qt-basic
/usr/share/clr-bundles/qt-basic-dev
/usr/share/clr-bundles/quassel
/usr/share/clr-bundles/ruby-basic
/usr/share/clr-bundles/runtime-libs-boost
/usr/share/clr-bundles/rust-basic
/usr/share/clr-bundles/scm-server
/usr/share/clr-bundles/service-os
/usr/share/clr-bundles/service-os-dev
/usr/share/clr-bundles/shells
/usr/share/clr-bundles/software-defined-cockpit
/usr/share/clr-bundles/software-defined-cockpit-dev
/usr/share/clr-bundles/software-testing
/usr/share/clr-bundles/storage-cluster
/usr/share/clr-bundles/storage-utils
/usr/share/clr-bundles/storage-utils-dev
/usr/share/clr-bundles/stream-server
/usr/share/clr-bundles/synergy
/usr/share/clr-bundles/sysadmin-basic
/usr/share/clr-bundles/sysadmin-basic-dev
/usr/share/clr-bundles/sysadmin-hostmgmt
/usr/share/clr-bundles/sysadmin-remote
/usr/share/clr-bundles/systemd-cryptsetup
/usr/share/clr-bundles/tcl-basic
/usr/share/clr-bundles/telemetrics
/usr/share/clr-bundles/time-server-basic
/usr/share/clr-bundles/user-basic
/usr/share/clr-bundles/user-basic-dev
/usr/share/clr-bundles/vim
/usr/share/clr-bundles/virt-manager
/usr/share/clr-bundles/virt-manager-gui
/usr/share/clr-bundles/vnc-server
/usr/share/clr-bundles/web-server-basic
/usr/share/clr-bundles/wireshark
/usr/share/clr-bundles/x11-server
/usr/share/clr-bundles/x11-tools
/usr/share/clr-bundles/xfce4-desktop
